baseURL = "https://technicalhat.github.io/drinktober-web/"
languageCode = "en-us"
title = "Drinktober 2019"
theme = "drinktober"
RelativeURLs=true
CanonifyURLs=true
[params]
    keywords = "meta keyword test"
